include("ccd-helper.jl")
initialize_cc_variables()
T2 = initialize_t2_only()
serialize("T2_vvoo.jlbin",T2)
nv = deserialize("nv.jlbin")
nocc = deserialize("nocc.jlbin")
R2u = zeros(Float64,nv,nv,nocc,nocc)
R2 = zeros(Float64,nv,nv,nocc,nocc)
R2 = calculate_residual_memeff(T2)
@code_warntype calculate_residual_memeff(T2)
serialize("T2.jlbin",T2)
R2 = calcresnew(T2)
T2_vvoo = deserialize("T2_vvoo.jlbin");
R = calcresnew(T2_vvoo)