using TensorOperations, Serialization
begin

    nv = deserialize("nv.jlbin")
    no = deserialize("no.jlbin")
    I_vvoo = zeros(Float64, nv, nv, no, no)
    g_oooo = deserialize("g_oooo.jlbin")
    INTpp_vvoo = deserialize("INTpp_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 1 / 2 * g_oooo[i_3, i_4, i_1, i_2] * INTpp_vvoo[a_1, a_2, i_3, i_4]
    INTpp_vvoo = nothing
    g_oooo = nothing
    g_vvoo = deserialize("g_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 1 / 2 * g_vvoo[a_1, a_2, i_1, i_2]
    g_vvoo = nothing
    g_vvvo = deserialize("g_vvvo.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += g_vvvo[a_2, a_1, a_3, i_1] * T1_vo[a_3, i_2]
    T1_vo = nothing
    g_vvvo = nothing
    g_voov = deserialize("g_voov.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * g_voov[a_2, i_3, i_2, a_3] * T2_vvoo[a_1, a_3, i_3, i_1]
    T2_vvoo = nothing
    g_voov = nothing
    g_vooo = deserialize("g_vooo.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * g_vooo[a_1, i_3, i_1, i_2] * T1_vo[a_2, i_3]
    T1_vo = nothing
    g_vooo = nothing
    g_vovo = deserialize("g_vovo.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * g_vovo[a_2, i_3, a_3, i_1] * T2_vvoo[a_1, a_3, i_3, i_2]
    T2_vvoo = nothing
    g_vovo = nothing
    g_voov = deserialize("g_voov.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 2 * g_voov[a_2, i_3, i_2, a_3] * T2_vvoo[a_1, a_3, i_1, i_3]
    T2_vvoo = nothing
    g_voov = nothing
    g_vovo = deserialize("g_vovo.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * g_vovo[a_1, i_3, a_3, i_1] * T2_vvoo[a_2, a_3, i_2, i_3]
    T2_vvoo = nothing
    g_vovo = nothing
    f_vv = deserialize("f_vv.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += f_vv[a_2, a_3] * T2_vvoo[a_1, a_3, i_1, i_2]
    T2_vvoo = nothing
    f_vv = nothing
    g_vvvv = deserialize("g_vvvv.jlbin")
    INTpp_vvoo = deserialize("INTpp_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 1 / 2 * g_vvvv[a_1, a_2, a_3, a_4] * INTpp_vvoo[a_3, a_4, i_1, i_2]
    INTpp_vvoo = nothing
    g_vvvv = nothing
    f_oo = deserialize("f_oo.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * f_oo[i_3, i_2] * T2_vvoo[a_1, a_2, i_1, i_3]
    T2_vvoo = nothing
    f_oo = nothing
    I_oo = zeros(Float64, no, no)
    g_oovo = deserialize("g_oovo.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_oo[i_4, i_2] += g_oovo[i_3, i_4, a_3, i_2] * T1_vo[a_3, i_3]
    T1_vo = nothing
    g_oovo = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -2 * I_oo[i_4, i_2] * T2_vvoo[a_1, a_2, i_1, i_4]
    T2_vvoo = nothing
    I_oo = nothing
    I_vovo = zeros(Float64, nv, no, nv, no)
    g_oovv = deserialize("g_oovv.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vovo[a_1, i_4, a_4, i_1] += g_oovv[i_3, i_4, a_3, a_4] * T2_vvoo[a_1, a_3, i_1, i_3]
    T2_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 2 * I_vovo[a_1, i_4, a_4, i_1] * T2_vvoo[a_2, a_4, i_2, i_4]
    T2_vvoo = nothing
    I_vovo = nothing
    I_oooo = zeros(Float64, no, no, no, no)
    g_oovo = deserialize("g_oovo.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_oooo[i_3, i_4, i_1, i_2] += g_oovo[i_3, i_4, a_3, i_1] * T1_vo[a_3, i_2]
    T1_vo = nothing
    g_oovo = nothing
    INTpp_vvoo = deserialize("INTpp_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_oooo[i_3, i_4, i_1, i_2] * INTpp_vvoo[a_1, a_2, i_4, i_3]
    INTpp_vvoo = nothing
    I_oooo = nothing
    I_oo = zeros(Float64, no, no)
    g_oovv = deserialize("g_oovv.jlbin")
    INTpp_vvoo = deserialize("INTpp_vvoo.jlbin")
    @tensor I_oo[i_4, i_2] += g_oovv[i_3, i_4, a_3, a_4] * INTpp_vvoo[a_3, a_4, i_3, i_2]
    INTpp_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -2 * I_oo[i_4, i_2] * T2_vvoo[a_1, a_2, i_1, i_4]
    T2_vvoo = nothing
    I_oo = nothing
    I_vovo = zeros(Float64, nv, no, nv, no)
    g_oovv = deserialize("g_oovv.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vovo[a_1, i_3, a_4, i_1] += g_oovv[i_3, i_4, a_3, a_4] * T2_vvoo[a_1, a_3, i_1, i_4]
    T2_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_vovo[a_1, i_3, a_4, i_1] * T2_vvoo[a_2, a_4, i_3, i_2]
    T2_vvoo = nothing
    I_vovo = nothing
    I_vovo = zeros(Float64, nv, no, nv, no)
    g_vovv = deserialize("g_vovv.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vovo[a_2, i_3, a_4, i_2] += g_vovv[a_2, i_3, a_3, a_4] * T1_vo[a_3, i_2]
    T1_vo = nothing
    g_vovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 2 * I_vovo[a_2, i_3, a_4, i_2] * T2_vvoo[a_1, a_4, i_1, i_3]
    T2_vvoo = nothing
    I_vovo = nothing
    I_vovo = zeros(Float64, nv, no, nv, no)
    g_vovv = deserialize("g_vovv.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vovo[a_2, i_3, a_4, i_2] += g_vovv[a_2, i_3, a_3, a_4] * T1_vo[a_3, i_2]
    T1_vo = nothing
    g_vovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * I_vovo[a_2, i_3, a_4, i_2] * T2_vvoo[a_1, a_4, i_3, i_1]
    T2_vvoo = nothing
    I_vovo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    g_voov = deserialize("g_voov.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vooo[a_2, i_3, i_1, i_2] += g_voov[a_2, i_3, i_2, a_3] * T1_vo[a_3, i_1]
    T1_vo = nothing
    g_voov = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * I_vooo[a_2, i_3, i_1, i_2] * T1_vo[a_1, i_3]
    T1_vo = nothing
    I_vooo = nothing
    I_vv = zeros(Float64, nv, nv)
    g_oovv = deserialize("g_oovv.jlbin")
    INTpp_vvoo = deserialize("INTpp_vvoo.jlbin")
    @tensor I_vv[a_2, a_4] += g_oovv[i_3, i_4, a_3, a_4] * INTpp_vvoo[a_2, a_3, i_3, i_4]
    INTpp_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_vv[a_2, a_4] * T2_vvoo[a_1, a_4, i_1, i_2]
    T2_vvoo = nothing
    I_vv = nothing
    I_oo = zeros(Float64, no, no)
    g_oovo = deserialize("g_oovo.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_oo[i_3, i_2] += g_oovo[i_3, i_4, a_3, i_2] * T1_vo[a_3, i_4]
    T1_vo = nothing
    g_oovo = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_oo[i_3, i_2] * T2_vvoo[a_1, a_2, i_1, i_3]
    T2_vvoo = nothing
    I_oo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    g_oovo = deserialize("g_oovo.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vooo[a_1, i_3, i_1, i_2] += g_oovo[i_3, i_4, a_3, i_1] * T2_vvoo[a_1, a_3, i_4, i_2]
    T2_vvoo = nothing
    g_oovo = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_vooo[a_1, i_3, i_1, i_2] * T1_vo[a_2, i_3]
    T1_vo = nothing
    I_vooo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    g_oovo = deserialize("g_oovo.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vooo[a_1, i_4, i_1, i_2] += g_oovo[i_3, i_4, a_3, i_2] * T2_vvoo[a_1, a_3, i_3, i_1]
    T2_vvoo = nothing
    g_oovo = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_vooo[a_1, i_4, i_1, i_2] * T1_vo[a_2, i_4]
    T1_vo = nothing
    I_vooo = nothing
    I_vovo = zeros(Float64, nv, no, nv, no)
    g_oovv = deserialize("g_oovv.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vovo[a_1, i_4, a_4, i_1] += g_oovv[i_3, i_4, a_3, a_4] * T2_vvoo[a_1, a_3, i_3, i_1]
    T2_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 1 / 2 * I_vovo[a_1, i_4, a_4, i_1] * T2_vvoo[a_2, a_4, i_4, i_2]
    T2_vvoo = nothing
    I_vovo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    g_vovo = deserialize("g_vovo.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vooo[a_1, i_3, i_1, i_2] += g_vovo[a_1, i_3, a_3, i_2] * T1_vo[a_3, i_1]
    T1_vo = nothing
    g_vovo = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * I_vooo[a_1, i_3, i_1, i_2] * T1_vo[a_2, i_3]
    T1_vo = nothing
    I_vooo = nothing
    I_vovo = zeros(Float64, nv, no, nv, no)
    g_oovv = deserialize("g_oovv.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vovo[a_1, i_3, a_3, i_1] += g_oovv[i_3, i_4, a_3, a_4] * T2_vvoo[a_1, a_4, i_1, i_4]
    T2_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -2 * I_vovo[a_1, i_3, a_3, i_1] * T2_vvoo[a_2, a_3, i_3, i_2]
    T2_vvoo = nothing
    I_vovo = nothing
    I_vovo = zeros(Float64, nv, no, nv, no)
    g_vovv = deserialize("g_vovv.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vovo[a_2, i_3, a_3, i_2] += g_vovv[a_2, i_3, a_3, a_4] * T1_vo[a_4, i_2]
    T1_vo = nothing
    g_vovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * I_vovo[a_2, i_3, a_3, i_2] * T2_vvoo[a_1, a_3, i_1, i_3]
    T2_vvoo = nothing
    I_vovo = nothing
    I_vovo = zeros(Float64, nv, no, nv, no)
    g_vovv = deserialize("g_vovv.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vovo[a_1, i_3, a_3, i_2] += g_vovv[a_1, i_3, a_3, a_4] * T1_vo[a_4, i_2]
    T1_vo = nothing
    g_vovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * I_vovo[a_1, i_3, a_3, i_2] * T2_vvoo[a_2, a_3, i_3, i_1]
    T2_vvoo = nothing
    I_vovo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    g_oovo = deserialize("g_oovo.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vooo[a_1, i_3, i_1, i_2] += g_oovo[i_3, i_4, a_3, i_2] * T2_vvoo[a_1, a_3, i_1, i_4]
    T2_vvoo = nothing
    g_oovo = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_vooo[a_1, i_3, i_1, i_2] * T1_vo[a_2, i_3]
    T1_vo = nothing
    I_vooo = nothing
    I_vv = zeros(Float64, nv, nv)
    g_oovv = deserialize("g_oovv.jlbin")
    INTpp_vvoo = deserialize("INTpp_vvoo.jlbin")
    @tensor I_vv[a_2, a_4] += g_oovv[i_3, i_4, a_3, a_4] * INTpp_vvoo[a_2, a_3, i_4, i_3]
    INTpp_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -2 * I_vv[a_2, a_4] * T2_vvoo[a_1, a_4, i_1, i_2]
    T2_vvoo = nothing
    I_vv = nothing
    I_vovo = zeros(Float64, nv, no, nv, no)
    g_oovv = deserialize("g_oovv.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vovo[a_1, i_4, a_3, i_1] += g_oovv[i_3, i_4, a_3, a_4] * T2_vvoo[a_1, a_4, i_1, i_3]
    T2_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * I_vovo[a_1, i_4, a_3, i_1] * T2_vvoo[a_2, a_3, i_2, i_4]
    T2_vvoo = nothing
    I_vovo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    g_oovo = deserialize("g_oovo.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vooo[a_1, i_4, i_1, i_2] += g_oovo[i_3, i_4, a_3, i_2] * T2_vvoo[a_1, a_3, i_1, i_3]
    T2_vvoo = nothing
    g_oovo = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -2 * I_vooo[a_1, i_4, i_1, i_2] * T1_vo[a_2, i_4]
    T1_vo = nothing
    I_vooo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    g_vovv = deserialize("g_vovv.jlbin")
    INTpp_vvoo = deserialize("INTpp_vvoo.jlbin")
    @tensor I_vooo[a_1, i_3, i_1, i_2] += g_vovv[a_1, i_3, a_3, a_4] * INTpp_vvoo[a_3, a_4, i_1, i_2]
    INTpp_vvoo = nothing
    g_vovv = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * I_vooo[a_1, i_3, i_1, i_2] * T1_vo[a_2, i_3]
    T1_vo = nothing
    I_vooo = nothing
    I_oooo = zeros(Float64, no, no, no, no)
    g_oovv = deserialize("g_oovv.jlbin")
    INTpp_vvoo = deserialize("INTpp_vvoo.jlbin")
    @tensor I_oooo[i_3, i_4, i_1, i_2] += g_oovv[i_3, i_4, a_3, a_4] * INTpp_vvoo[a_3, a_4, i_1, i_2]
    INTpp_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 1 / 2 * I_oooo[i_3, i_4, i_1, i_2] * T2_vvoo[a_1, a_2, i_3, i_4]
    T2_vvoo = nothing
    I_oooo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    I_oooo = zeros(Float64, no, no, no, no)
    g_oovv = deserialize("g_oovv.jlbin")
    INTpp_vvoo = deserialize("INTpp_vvoo.jlbin")
    @tensor I_oooo[i_3, i_4, i_1, i_2] += g_oovv[i_3, i_4, a_3, a_4] * INTpp_vvoo[a_3, a_4, i_1, i_2]
    INTpp_vvoo = nothing
    g_oovv = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vooo[a_1, i_4, i_1, i_2] += I_oooo[i_3, i_4, i_1, i_2] * T1_vo[a_1, i_3]
    T1_vo = nothing
    I_oooo = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 1 / 2 * I_vooo[a_1, i_4, i_1, i_2] * T1_vo[a_2, i_4]
    T1_vo = nothing
    I_vooo = nothing
    I_oo = zeros(Float64, no, no)
    g_oovv = deserialize("g_oovv.jlbin")
    INTpp_vvoo = deserialize("INTpp_vvoo.jlbin")
    @tensor I_oo[i_4, i_2] += g_oovv[i_3, i_4, a_3, a_4] * INTpp_vvoo[a_3, a_4, i_2, i_3]
    INTpp_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_oo[i_4, i_2] * T2_vvoo[a_1, a_2, i_1, i_4]
    T2_vvoo = nothing
    I_oo = nothing
    I_vv = zeros(Float64, nv, nv)
    g_vovv = deserialize("g_vovv.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vv[a_2, a_4] += g_vovv[a_2, i_3, a_3, a_4] * T1_vo[a_3, i_3]
    T1_vo = nothing
    g_vovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * I_vv[a_2, a_4] * T2_vvoo[a_1, a_4, i_1, i_2]
    T2_vvoo = nothing
    I_vv = nothing
    I_vv = zeros(Float64, nv, nv)
    g_vovv = deserialize("g_vovv.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vv[a_2, a_3] += g_vovv[a_2, i_3, a_3, a_4] * T1_vo[a_4, i_3]
    T1_vo = nothing
    g_vovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 2 * I_vv[a_2, a_3] * T2_vvoo[a_1, a_3, i_1, i_2]
    T2_vvoo = nothing
    I_vv = nothing
    I_oo = zeros(Float64, no, no)
    f_ov = deserialize("f_ov.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_oo[i_3, i_2] += f_ov[i_3, a_3] * T1_vo[a_3, i_2]
    T1_vo = nothing
    f_ov = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * I_oo[i_3, i_2] * T2_vvoo[a_1, a_2, i_1, i_3]
    T2_vvoo = nothing
    I_oo = nothing
    I_vovo = zeros(Float64, nv, no, nv, no)
    g_oovv = deserialize("g_oovv.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vovo[a_1, i_4, a_3, i_2] += g_oovv[i_3, i_4, a_3, a_4] * T2_vvoo[a_1, a_4, i_3, i_2]
    T2_vvoo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += 1 / 2 * I_vovo[a_1, i_4, a_3, i_2] * T2_vvoo[a_2, a_3, i_4, i_1]
    T2_vvoo = nothing
    I_vovo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    f_ov = deserialize("f_ov.jlbin")
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vooo[a_1, i_3, i_1, i_2] += f_ov[i_3, a_3] * T2_vvoo[a_1, a_3, i_1, i_2]
    T2_vvoo = nothing
    f_ov = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -1 * I_vooo[a_1, i_3, i_1, i_2] * T1_vo[a_2, i_3]
    T1_vo = nothing
    I_vooo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    I_oovo = zeros(Float64, no, no, nv, no)
    g_oovv = deserialize("g_oovv.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_oovo[i_3, i_4, a_4, i_1] += g_oovv[i_3, i_4, a_3, a_4] * T1_vo[a_3, i_1]
    T1_vo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vooo[a_2, i_4, i_1, i_2] += I_oovo[i_3, i_4, a_4, i_1] * T2_vvoo[a_2, a_4, i_2, i_3]
    T2_vvoo = nothing
    I_oovo = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_vooo[a_2, i_4, i_1, i_2] * T1_vo[a_1, i_4]
    T1_vo = nothing
    I_vooo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    I_oovo = zeros(Float64, no, no, nv, no)
    g_oovv = deserialize("g_oovv.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_oovo[i_3, i_4, a_4, i_1] += g_oovv[i_3, i_4, a_3, a_4] * T1_vo[a_3, i_1]
    T1_vo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vooo[a_2, i_3, i_1, i_2] += I_oovo[i_3, i_4, a_4, i_1] * T2_vvoo[a_2, a_4, i_2, i_4]
    T2_vvoo = nothing
    I_oovo = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += -2 * I_vooo[a_2, i_3, i_1, i_2] * T1_vo[a_1, i_3]
    T1_vo = nothing
    I_vooo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    I_oovo = zeros(Float64, no, no, nv, no)
    g_oovv = deserialize("g_oovv.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_oovo[i_3, i_4, a_4, i_1] += g_oovv[i_3, i_4, a_3, a_4] * T1_vo[a_3, i_1]
    T1_vo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vooo[a_1, i_4, i_1, i_2] += I_oovo[i_3, i_4, a_4, i_1] * T2_vvoo[a_1, a_4, i_3, i_2]
    T2_vvoo = nothing
    I_oovo = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_vooo[a_1, i_4, i_1, i_2] * T1_vo[a_2, i_4]
    T1_vo = nothing
    I_vooo = nothing
    I_vooo = zeros(Float64, nv, no, no, no)
    I_oovo = zeros(Float64, no, no, nv, no)
    g_oovv = deserialize("g_oovv.jlbin")
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_oovo[i_3, i_4, a_4, i_1] += g_oovv[i_3, i_4, a_3, a_4] * T1_vo[a_3, i_1]
    T1_vo = nothing
    g_oovv = nothing
    T2_vvoo = deserialize("T2_vvoo.jlbin")
    @tensor I_vooo[a_2, i_3, i_1, i_2] += I_oovo[i_3, i_4, a_4, i_1] * T2_vvoo[a_2, a_4, i_4, i_2]
    T2_vvoo = nothing
    I_oovo = nothing
    T1_vo = deserialize("T1_vo.jlbin")
    @tensor I_vvoo[a_1, a_2, i_1, i_2] += I_vooo[a_2, i_3, i_1, i_2] * T1_vo[a_1, i_3]
    T1_vo = nothing
    I_vooo = nothing
    @tensor R2[a,b,i,j] := I_vvoo[a,b,i,j] + I_vvoo[b,a,j,i]
    return R2
end